import sys
sys.path.insert(0, "/Users/etrexkuo/toprankland/scripts")
from daily_helper import load, save, upsert, last_rankings
DATE = "2026-06-03"


def do(fname, references, en_comm, en_hl, zh_comm, zh_hl):
    d, p = load(fname)
    entry = {"date": DATE, "rankings": last_rankings(d), "references": references,
             "i18n": {"en": {"commentary": en_comm, "highlights": en_hl},
                      "zh-tw": {"commentary": zh_comm, "highlights": zh_hl}}}
    upsert(d, entry)
    save(p, d)
    print("OK", fname)


# ---------------- Bluetooth speakers ----------------
do("best-bluetooth-speakers.json",
   [{"title": "The 6 Best Bluetooth Speakers of 2026", "url": "https://www.rtings.com/speaker/reviews/best/by-feature/bluetooth", "source": "RTINGS"},
    {"title": "Best Bluetooth speakers 2026: tried and tested for every budget", "url": "https://www.whathifi.com/best-buys/best-bluetooth-speakers-portable-speakers-for-every-budget", "source": "What Hi-Fi?"},
    {"title": "The best Bluetooth speakers 2026: Which should you buy?", "url": "https://www.soundguys.com/best-bluetooth-speakers-2488/", "source": "SoundGuys"}],
   "The JBL Charge 6 stays at the top for me, and this week's RTINGS roundup reinforces why. It pairs strong bass and clear mids with an IP68 rating and a 24 hour battery, which is the exact combination most people actually want from a grab and go speaker. At its current price it is the speaker I hand to friends who ask for one recommendation. The JBL Boombox 4 deserves a callout too, with its 40 hour battery making it the party box of choice when you need volume that fills a backyard. The Marshall Emberton III holds second on the strength of its tuning and that retro design that still turns heads, and the Bose SoundLink Max keeps third because nothing in its size class matches its low end control and polish. I considered nudging the Anker Soundcore Motion X600 up after SoundGuys praised its multi driver setup and immersive presentation, but the difference is marginal and I want to see it hold over a few more weeks before moving it. The Sonos pair anchors the home leaning middle of the list for listeners who care more about app ecosystem and multi room than rugged portability. Nothing in the past week shifts the order. JBL continues to own the value conversation, Marshall and Bose own the design and refinement lane, and the rankings reflect that split cleanly.",
   [{"title": "JBL Charge 6 is still the one to buy", "body": "RTINGS again names the Charge 6 the best for most people, and the math is simple. Strong bass, good clarity, IP68 dust and water resistance, and 24 hours of playback in a body you can sling in a bag. That balance is why it holds rank 1."},
    {"title": "Boombox 4 is the backyard party answer", "body": "With 40 hours of battery on a single charge and output that genuinely fills outdoor space, the Boombox 4 is the speaker to reach for when the gathering is large. It earns its place as the high volume specialist on this list."},
    {"title": "Marshall and Bose own refinement", "body": "The Emberton III and SoundLink Max are not the loudest or the most rugged, but their tuning, build, and design polish keep them ahead of cheaper rivals. They are the picks for listeners who want a speaker that looks and sounds considered."}],
   "JBL Charge 6 對我來說還是穩坐第一，這週 RTINGS 的整理又再次說明原因。它把扎實的低頻、清楚的中頻、IP68 防塵防水跟 24 小時續航全包進一台可以隨手帶著走的機身裡，老實說這就是大多數人真正想要的組合。朋友問我只推一台的話，我直接遞這台給他。JBL Boombox 4 也值得一提，40 小時續航讓它成為烤肉聚會、需要把整個後院灌滿音量時的首選。Marshall Emberton III 靠著調音跟那個到現在還是很吸睛的復古外型守住第二，Bose SoundLink Max 則是因為同尺寸找不到對手能比它的低頻控制力跟質感，所以第三穩穩的。我本來想把 Anker Soundcore Motion X600 往上挪，畢竟 SoundGuys 誇它多單體配置跟沉浸感，可是差距其實不大，我想再觀察幾週看它撐不撐得住再說。Sonos 那兩台則是顧好偏居家、重視 App 生態跟多房間的中段族群。這週沒有任何消息能撼動排序，JBL 繼續主導 CP 值話題，Marshall 跟 Bose 顧好設計跟細膩度這條線，排名乾淨俐落地反映了這個分工。",
   [{"title": "JBL Charge 6 還是首選", "body": "RTINGS 再次把 Charge 6 評為最適合大多數人的選擇，道理很簡單。扎實低頻、清楚音質、IP68 防塵防水，加上 24 小時播放，全塞進一個丟進包包就能走的機身。這個平衡就是它穩坐第一的原因。"},
    {"title": "Boombox 4 是烤肉聚會的答案", "body": "單次充電 40 小時續航，加上能真正灌滿戶外空間的音量，人多場合就是要它。它在這份榜單上扮演大音量專家的角色，名次拿得實至名歸。"},
    {"title": "Marshall 跟 Bose 顧質感這條線", "body": "Emberton III 跟 SoundLink Max 不是最大聲也不是最耐操，但調音、做工跟設計質感讓它們穩穩壓過便宜對手。想要一台看起來聽起來都有用心的喇叭，就選這兩台。"}])

# ---------------- Noise cancelling headphones ----------------
do("best-noise-cancelling-headphones.json",
   [{"title": "The 5 Best Noise Cancelling Headphones of 2026", "url": "https://www.rtings.com/headphones/reviews/best/by-feature/noise-cancelling", "source": "RTINGS"},
    {"title": "Best noise-cancelling headphones 2026 - tested by our in-house review experts", "url": "https://www.whathifi.com/best-buys/headphones/best-noise-cancelling-headphones", "source": "What Hi-Fi?"},
    {"title": "11 Best Noise-Canceling Headphones of 2026: Top Tested, Reviewed Picks", "url": "https://www.rollingstone.com/product-recommendations/tech/best-noise-canceling-headphones-1235398146/", "source": "Rolling Stone"}],
   "The Sony WH-1000XM6 stays at number one, and RTINGS continues to call it the best noise cancelling headphone you can buy as a true all rounder. That is exactly how I see it. The ANC is class leading, the tuning is balanced enough to please most listeners out of the box, and the comfort holds up over long flights. The Bose QuietComfort Ultra keeps second because its noise cancelling is still the most complete I have heard across the frequency range, and reviewers this week again flagged that Bose reduces low rumble more capably than rivals. If pure silence is your priority, that is the pair to get. The Sennheiser Momentum 4 holds third on the strength of its long battery life and warm, easy listening sound, with the Sennheiser HDB 630 right behind as the audiophile leaning option for people who care more about detail than active cancelling. The Apple AirPods Max remains the strongest pick inside the Apple ecosystem, with ambient mode that several outlets still rate among the most natural. Lower down, the Soundcore Space pair continues to be the value story, delivering most of the experience for a fraction of the flagship price. Nothing this week changes the order. Sony leads on balance, Bose leads on raw cancelling, and the rest of the field sorts cleanly by priority.",
   [{"title": "Sony WH-1000XM6 is the all rounder to beat", "body": "RTINGS names it the best noise cancelling headphone overall, and the reasoning matches mine. Top tier ANC, balanced tuning that needs no EQ fiddling, and comfort that survives long haul flights. That combination keeps it at rank 1."},
    {"title": "Bose QuietComfort Ultra wins on raw silence", "body": "Reviewers this week again confirmed Bose reduces sound across the frequency range more capably than any rival, especially low rumble. If your single priority is the quietest possible cabin, this is the pair to buy."},
    {"title": "Soundcore Space is the value play", "body": "The Space 2 and Space Q45 deliver the bulk of the flagship experience, solid ANC and pleasant sound, at a fraction of the price. They are the easy recommendation for anyone who wants strong cancelling without paying flagship money."}],
   "Sony WH-1000XM6 還是第一，RTINGS 這週繼續把它列為最會的全能選手，老實說我也是這樣看的。降噪頂級、出廠調音夠平衡讓大多數人直接用就滿意、長途飛行戴起來也撐得住。Bose QuietComfort Ultra 守住第二，因為它的降噪在整個頻段範圍內還是我聽過最完整的，這週評測又再次點出 Bose 壓低頻隆隆聲比對手更行。如果你只在乎安靜，就買這支。Sennheiser Momentum 4 靠長續航跟溫暖耐聽的聲音守住第三，Sennheiser HDB 630 緊跟在後，是給那種重視細節勝過主動降噪的發燒友選的。Apple AirPods Max 仍然是 Apple 生態裡最強的選擇，環境音模式好幾家媒體還是評為最自然的之一。再往下，Soundcore Space 那兩支繼續講 CP 值的故事，花零頭的價錢就能拿到大部分的體驗。這週沒有任何消息改動排序，Sony 贏在平衡，Bose 贏在純降噪實力，剩下的就照需求乾淨地排好。",
   [{"title": "Sony WH-1000XM6 是要被超越的全能王", "body": "RTINGS 把它列為整體最佳降噪耳機，理由跟我的看法一致。頂級降噪、不用調 EQ 就平衡的調音、撐得過長程飛行的舒適度。這個組合讓它穩坐第一。"},
    {"title": "Bose QuietComfort Ultra 贏在純粹的安靜", "body": "這週評測再次確認 Bose 在整個頻段壓制聲音比任何對手都行，低頻隆隆聲尤其明顯。如果你唯一的需求就是機艙裡最安靜的那支，買它就對了。"},
    {"title": "Soundcore Space 是 CP 值首選", "body": "Space 2 跟 Space Q45 用零頭的價錢給你旗艦大部分的體驗，紮實降噪加上好聽的聲音。想要強降噪又不想花旗艦的錢，這就是最好推的選擇。"}])

# ---------------- Wireless earbuds ----------------
do("best-wireless-earbuds.json",
   [{"title": "The 7 Best Wireless Earbuds of 2026", "url": "https://www.rtings.com/headphones/reviews/best/wireless-earbuds", "source": "RTINGS"},
    {"title": "Best wireless earbuds 2026: 7 sensational pairs reviewed and rated by our experts", "url": "https://www.whathifi.com/best-buys/best-wireless-earbuds-budget-and-premium", "source": "What Hi-Fi?"},
    {"title": "The best wireless earbuds of 2026: Lab-tested by experts", "url": "https://www.soundguys.com/best-wireless-earbuds-2-14313/", "source": "SoundGuys"}],
   "The Sony WF-1000XM6 holds number one, and this week's RTINGS roundup again crowns it the best wireless earbuds you can buy. The numbers back it up. Around 88 percent average noise reduction across frequencies, a 4.8 out of 5 MDAQS sound score, and an AI beamforming mic system trained on a huge voice sample set that finally makes these genuinely good for calls. That is a flagship that earns its place. The AirPods Pro 3 stay at second as the best pick for anyone in the Apple world, with several outlets still rating their noise cancelling among the very best on the market. The Bose QuietComfort Ultra Earbuds 2nd Gen keep third, and reviewers this week reaffirmed that the second gen fixed the connectivity quirks and added wireless charging while keeping top tier cancelling. The Samsung Galaxy Buds 4 Pro and the older Sony XM5 fill the middle for listeners tied to a platform or hunting a discount on last year's flagship. The Jabra Elite 10 anchors the list on battery and fit. Nothing this week moves the order. Sony leads on measured performance, Apple leads inside its ecosystem, and Bose leads on pure quiet.",
   [{"title": "Sony WF-1000XM6 is the measured leader", "body": "RTINGS again names it the best wireless earbuds overall. Roughly 88 percent average noise reduction, a 4.8 out of 5 MDAQS sound score, and an AI beamforming mic make it the rare flagship that excels at music, ANC, and calls all at once."},
    {"title": "AirPods Pro 3 own the Apple ecosystem", "body": "For iPhone users the Pro 3 are the obvious pick, with noise cancelling that multiple outlets still rate among the best available and the seamless handoff and spatial audio that only Apple delivers. That keeps them firmly at rank 2."},
    {"title": "Bose QC Ultra 2nd Gen fixed the gripes", "body": "Reviewers confirm the second generation cleared the connectivity issues and added wireless charging while preserving Bose's top tier cancelling. It stays at third as the pick for listeners who prize silence above all."}],
   "Sony WF-1000XM6 守住第一，這週 RTINGS 的整理又把它封為最值得買的真無線耳機。數據撐得住這個地位。全頻段平均約 88% 降噪、MDAQS 音質 4.8 分（滿分 5），加上用龐大語音樣本訓練的 AI 波束成形麥克風，這次終於讓它通話也真的能打。這種旗艦對得起它的位置。AirPods Pro 3 守住第二，是 Apple 圈子裡的首選，好幾家媒體到現在還是把它的降噪評為市場上最頂之一。Bose QuietComfort Ultra Earbuds 二代守第三，這週評測再次確認二代修好了連線的小毛病、加上無線充電，又保住頂級降噪。Samsung Galaxy Buds 4 Pro 跟舊款 Sony XM5 填中段，給綁定平台或想撿去年旗艦折扣的人選。Jabra Elite 10 靠續航跟配戴感守住榜尾。這週沒消息能動排序。Sony 贏在實測數據，Apple 贏在自家生態，Bose 贏在純粹的安靜。",
   [{"title": "Sony WF-1000XM6 是數據王", "body": "RTINGS 再次把它列為整體最佳真無線耳機。全頻段約 88% 平均降噪、MDAQS 音質 4.8 分、AI 波束成形麥克風，讓它成為少見的音樂、降噪、通話一次到位的旗艦。"},
    {"title": "AirPods Pro 3 主宰 Apple 生態", "body": "iPhone 用戶選它最直覺，降噪被好幾家媒體評為市場最頂之一，還有只有 Apple 給得起的無縫切換跟空間音訊。這讓它穩穩守在第二。"},
    {"title": "Bose QC Ultra 二代修好了缺點", "body": "評測確認二代清掉了連線問題、加上無線充電，同時保住 Bose 頂級降噪。它守住第三，是把安靜擺第一的人的選擇。"}])

# ---------------- Gaming headsets ----------------
do("best-gaming-headsets.json",
   [{"title": "The 6 Best Wireless Gaming Headsets of 2026", "url": "https://www.rtings.com/headphones/reviews/best/wireless-gaming-headsets", "source": "RTINGS"},
    {"title": "Best Wireless Gaming Headsets 2026: Our Tested Picks for Bluetooth, Budget, and More", "url": "https://www.tomshardware.com/best-picks/best-wireless-headsets", "source": "Tom's Hardware"},
    {"title": "Best Gaming Headsets 2026: Our Tested Picks for Comfort, Connectivity, and Communication", "url": "https://www.tomshardware.com/peripherals/gaming-headsets/best-gaming-headsets", "source": "Tom's Hardware"}],
   "The SteelSeries Arctis Nova Pro Wireless keeps number one, and the reason is the same one that has held all year. The hot swap dual cell battery means you never stop gaming to charge, one cell powers the headset while the second tops up in the base station. For a daily driver that is the feature that actually matters, and RTINGS still rates it among the very top wireless options. The Audeze Maxwell 2 sits at second, and this week's roundup again calls it the best wireless gaming headset for pure sound, with planar magnetic drivers that add real weight to explosions and footsteps. If audio quality is your single priority, that is the pick. The Turtle Beach Stealth Pro II holds third with its docking station and ANC, a genuinely premium package even if its mic trails the Maxwell. The Logitech G Pro X 2 Lightspeed and Asus ROG Delta II fill the competitive middle where sub 20ms wireless latency is now standard, so the old wired versus wireless debate is effectively settled. Nothing this week reshuffles the order. SteelSeries leads on uptime, Audeze leads on sound, and the field below sorts cleanly by feature set.",
   [{"title": "SteelSeries Arctis Nova Pro Wireless wins on uptime", "body": "The hot swap dual cell system is the killer feature. One battery powers the headset while the spare charges in the base station, so you literally never stop to recharge. That practicality keeps it at rank 1 over flashier rivals."},
    {"title": "Audeze Maxwell 2 is the sound champion", "body": "This week's roundup again names it the best wireless headset for audio. Planar magnetic drivers deliver detail and low distortion with a slightly warm tuning that adds weight to explosions and footsteps. For sound first buyers it is the clear pick."},
    {"title": "Wireless latency is no longer a handicap", "body": "SteelSeries, Logitech, and HyperX wireless headsets now measure under 20ms latency on their 2.4GHz dongles. The competitive penalty for going wireless is effectively gone, which is why the top of this list is all wireless."}],
   "SteelSeries Arctis Nova Pro Wireless 守住第一，理由跟整年一樣。熱插拔雙電池代表你打遊戲打到一半永遠不用停下來充電，一顆供電給耳機、另一顆在底座充飽。對天天用的人來說這才是真正有感的功能，RTINGS 也還是把它列為最頂的無線選擇之一。Audeze Maxwell 2 排第二，這週的整理又把它封為純音質最佳的無線電競耳機，平面振膜單體讓爆炸聲跟腳步聲真的有重量。如果你只在乎音質，就選它。Turtle Beach Stealth Pro II 守第三，底座加 ANC，整體真的很高級，雖然麥克風還是輸 Maxwell 一截。Logitech G Pro X 2 Lightspeed 跟 Asus ROG Delta II 填競技中段，現在無線延遲低於 20ms 已經是標配，所以以前那個有線對無線的爭論基本上可以收了。這週沒消息動排序。SteelSeries 贏在不斷電，Audeze 贏在音質，下面的就照功能組合乾淨地排好。",
   [{"title": "SteelSeries Arctis Nova Pro Wireless 贏在不斷電", "body": "熱插拔雙電池是殺手鐧。一顆供電給耳機、備用那顆在底座充電，你字面上永遠不用停下來充。這個實用性讓它壓過外型更花俏的對手，穩坐第一。"},
    {"title": "Audeze Maxwell 2 是音質冠軍", "body": "這週整理又把它封為音質最佳的無線耳機。平面振膜單體帶來細節跟低失真，略偏暖的調音讓爆炸聲跟腳步聲都有重量。音質至上的人選它最準。"},
    {"title": "無線延遲已經不是包袱", "body": "SteelSeries、Logitech、HyperX 的無線耳機在 2.4GHz 接收器上現在都測在 20ms 以下。選無線的競技代價基本上消失了，這也是為什麼這份榜單前段全是無線。"}])

# ---------------- Smart speakers ----------------
do("best-smart-speakers.json",
   [{"title": "The 5 Best Smart Speakers of 2026", "url": "https://www.rtings.com/speaker/reviews/best/smart", "source": "RTINGS"},
    {"title": "Best smart speakers in 2026 - Alexa, Google, and Siri tested", "url": "https://www.tomsguide.com/us/best-smart-speakers,review-4480.html", "source": "Tom's Guide"},
    {"title": "Best smart speaker in 2026 with Google, Alexa and Siri built-in", "url": "https://www.stuff.tv/features/best-smart-speakers-tested/", "source": "Stuff"}],
   "The Amazon Echo Studio 2nd Gen stays at number one for me as the best balance of sound and smarts. It fills a room convincingly, the Alexa platform still has the broadest device support with over 140,000 certified integrations, and the price sits well below audiophile rivals. The Sonos Era 100 holds second because it is the speaker I point music first buyers toward, with cleaner stereo separation and the Sonos multi room ecosystem that nothing else quite matches. The Apple HomePod 2nd Gen keeps third as the obvious pick for iPhone households, with sound quality reviewers still rate as a genuine success even if Siri lags on smarts. The JBL Authentics 500 is worth a callout after this week's roundups again praised it as the rare speaker with simultaneous Alexa and Google support built in, useful if your home is split across ecosystems. Lower down, the Echo Dot Max and Echo Dot 5th Gen carry the budget end, punching above their size on volume and value. Nothing this week moves the order. Amazon leads on ecosystem breadth, Sonos leads on sound and multi room, and Apple leads inside its own walls. The list reflects that split as it stands.",
   [{"title": "Echo Studio 2nd Gen balances sound and smarts", "body": "It fills a room convincingly and ties into Alexa's 140,000 plus certified integrations, the broadest smart home support of any platform. At a price below audiophile rivals, that balance keeps it at rank 1."},
    {"title": "Sonos Era 100 is the music first pick", "body": "For listeners who care most about sound, the Era 100 delivers cleaner stereo and the Sonos multi room ecosystem that rivals still cannot match. It is the speaker I recommend when audio quality is the priority, which holds it at second."},
    {"title": "JBL Authentics 500 runs both assistants", "body": "This week's roundups again highlight it as the rare speaker with simultaneous built in Alexa and Google support. For homes split across ecosystems, that dual assistant flexibility is a genuinely useful and uncommon feature."}],
   "Amazon Echo Studio 二代對我來說還是第一，音質跟智慧的平衡最好。灌滿一個房間很有說服力，Alexa 平台到現在還是裝置支援最廣的，超過 14 萬個認證整合，價格又壓在發燒對手底下一截。Sonos Era 100 守第二，因為這是我推給音樂優先族的那台，立體聲分離更乾淨，Sonos 多房間生態也沒什麼東西比得上。Apple HomePod 二代守第三，是 iPhone 家庭最直覺的選擇，音質被評測認為真的成功，雖然 Siri 在智慧這塊還是落後。JBL Authentics 500 值得一提，這週的整理又稱讚它是少見內建可同時跑 Alexa 跟 Google 的喇叭，家裡跨生態的話很好用。再往下，Echo Dot Max 跟 Echo Dot 五代撐住預算端，音量跟 CP 值都超出體積該有的水準。這週沒消息動排序。Amazon 贏在生態廣度，Sonos 贏在音質跟多房間，Apple 贏在自家圈內。榜單就如實反映這個分工。",
   [{"title": "Echo Studio 二代平衡音質與智慧", "body": "灌滿房間很有說服力，又串接 Alexa 超過 14 萬個認證整合，是所有平台裡智慧家庭支援最廣的。價格還壓在發燒對手底下，這個平衡讓它穩坐第一。"},
    {"title": "Sonos Era 100 是音樂優先首選", "body": "對最在乎聲音的人來說，Era 100 給更乾淨的立體聲，加上對手還是比不上的 Sonos 多房間生態。音質擺第一時我就推這台，這讓它守住第二。"},
    {"title": "JBL Authentics 500 兩個助理一起跑", "body": "這週的整理又點出它是少見內建可同時跑 Alexa 跟 Google 的喇叭。家裡跨生態的話，這種雙助理彈性是真的好用又少見的功能。"}])

# ---------------- Soundbars ----------------
do("best-soundbars.json",
   [{"title": "The 6 Best Dolby Atmos Soundbars of 2026", "url": "https://www.rtings.com/soundbar/reviews/best/by-type/dolby-atmos", "source": "RTINGS"},
    {"title": "Best Dolby Atmos soundbars 2026: our reviewers' five recommendations", "url": "https://www.whathifi.com/best-buys/best-dolby-atmos-soundbars-the-best-atmos-tv-speakers", "source": "What Hi-Fi?"},
    {"title": "The best soundbars of CES 2026: Dolby Atmos FlexConnect, Audio by Bang & Olufsen", "url": "https://www.techradar.com/televisions/soundbars/the-best-soundbars-of-ces-2026-dolby-atmos-flexconnect-audio-by-bang-and-olufsen-and-icelandic-volcanoes", "source": "TechRadar"}],
   "The Samsung HW-Q990F stays at number one, and RTINGS again names it the best Dolby Atmos soundbar overall. The 11.1.4 configuration with discrete wireless satellites and four up firing drivers delivers detailed, rich audio that is genuinely hard to beat at any price. For a full surround experience out of one box it is still the package to buy. The Sonos Arc Ultra holds second as my pick for anyone who wants single bar elegance with serious Atmos height, plus the Sonos ecosystem for music when the TV is off. The Sony Bravia Theatre Bar 9 keeps third on the strength of its center channel clarity, which makes dialogue land cleanly without you reaching for a remote. The LG S95TR and Samsung HW-QS750F fill the upper middle for buyers who want big systems at a slightly lower entry point. Worth noting from CES coverage this week, the LG H7 is the first model with Dolby Atmos FlexConnect, which lets you add wireless speakers flexibly around the room, a feature I expect to matter more as the year goes on, though it does not change today's order. Samsung leads on full system immersion, Sonos leads on single bar polish, and Sony leads on dialogue. The ranking holds.",
   [{"title": "Samsung HW-Q990F is the surround champion", "body": "RTINGS again names it the best Dolby Atmos soundbar. The 11.1.4 setup with discrete wireless satellites and four up firing drivers delivers detail and staging few systems match at any price. For full surround from one purchase it stays at rank 1."},
    {"title": "Sonos Arc Ultra is the single bar pick", "body": "For buyers who want one elegant bar with real Atmos height and no satellites cluttering the room, the Arc Ultra is the answer, and it doubles as a capable music speaker through the Sonos ecosystem. That versatility holds it at second."},
    {"title": "Dolby Atmos FlexConnect arrives at CES", "body": "TechRadar's CES coverage flagged the LG H7 as the first soundbar with Dolby Atmos FlexConnect, which lets you place wireless speakers flexibly around the room. It is a feature to watch this year even though it does not shift today's rankings."}],
   "Samsung HW-Q990F 守住第一，RTINGS 又把它評為整體最佳 Dolby Atmos 聲霸。11.1.4 配置搭配獨立無線衛星喇叭跟四顆向上發聲單體，給出細膩又飽滿的音場，這個價位帶真的很難找到對手。想用一盒搞定完整環繞，它還是首選。Sonos Arc Ultra 守第二，是我推給想要單條優雅又要真正 Atmos 高度的人，電視關掉還能靠 Sonos 生態聽音樂。Sony Bravia Theatre Bar 9 靠中置聲道的清晰度守第三，對白乾淨地送到耳朵，不用一直拿遙控器調。LG S95TR 跟 Samsung HW-QS750F 填上中段，給想要大系統但入手價想低一點的人。這週 CES 報導裡值得一提，LG H7 是第一台搭 Dolby Atmos FlexConnect 的機型，可以在房間裡彈性加無線喇叭，這個功能我覺得隨著今年過去會越來越重要，不過目前還不影響排序。Samsung 贏在完整系統的沉浸感，Sonos 贏在單條的質感，Sony 贏在對白。排名維持不變。",
   [{"title": "Samsung HW-Q990F 是環繞冠軍", "body": "RTINGS 又把它評為最佳 Dolby Atmos 聲霸。11.1.4 配置加獨立無線衛星跟四顆向上單體，給出少有系統能在任何價位匹敵的細節跟音場。想一次買齊完整環繞，它穩坐第一。"},
    {"title": "Sonos Arc Ultra 是單條首選", "body": "想要一條優雅、有真正 Atmos 高度、又不想衛星喇叭塞滿房間的人，Arc Ultra 就是答案，透過 Sonos 生態還能兼當好用的音樂喇叭。這種多功能讓它守住第二。"},
    {"title": "Dolby Atmos FlexConnect 在 CES 登場", "body": "TechRadar 的 CES 報導點出 LG H7 是第一台搭 Dolby Atmos FlexConnect 的聲霸，可以在房間裡彈性擺放無線喇叭。雖然不影響今天的排名，這是今年值得關注的功能。"}])

print("ALL DONE")
