import sys
sys.path.insert(0, "/Users/etrexkuo/toprankland/scripts")
from daily_helper import load, save, upsert, last_rankings
DATE = "2026-06-03"

def do(fname, references, en_comm, en_hl, zh_comm, zh_hl):
    d, p = load(fname)
    entry = {"date": DATE, "rankings": last_rankings(d), "references": references,
             "i18n": {"en": {"commentary": en_comm, "highlights": en_hl},
                      "zh-tw": {"commentary": zh_comm, "highlights": zh_hl}}}
    upsert(d, entry); save(p, d); print("OK", fname)


# ---------------- Robot Vacuums ----------------
do("best-robot-vacuums.json",
   [{"title": "Best (June 2026) Robot Vacuums", "url": "https://vacuumwars.com/best-monthly-2026-robot-vacuums/", "source": "Vacuum Wars"},
    {"title": "The 4 Best Robot Vacuums of 2026", "url": "https://www.rtings.com/robot-vacuum/reviews/best/robot", "source": "RTINGS"},
    {"title": "Robot Vacuum: Best from $300 to $600 - June 2026", "url": "https://vacuumwars.com/best-robot-vacuum-under-600/", "source": "Vacuum Wars"}],
   "Heading into June the Dreame X60 Max Ultra stays my number one, and the latest monthly testing keeps confirming the call. Vacuum Wars still names it the best overall robot vacuum for June 2026, and it keeps that title by cleaning more consistently than anything else in the field. The combination of 35,000 Pa suction, the HyperStream Duo Divide anti-tangle brush, and the slim retractable-LiDAR profile means it handles deep carpet, flattened pet hair, and low-clearance furniture without me babysitting it. That is the whole point of paying flagship money, and the X60 earns it week after week.\n\nThe Roborock Saros 20 holds rank 2 as the navigation specialist. Its AdaptiLift chassis still crosses thresholds the rest of the field stalls on, so if your home has raised tile, thick transition strips, or a small step between rooms, this is the one that keeps going. The honest split remains the same: Dreame cleans a touch better, Roborock climbs and maps a touch better, and both are excellent.\n\nThe interesting story this month is downstream. Flagship features like roller mops, advanced obstacle avoidance, and self-emptying docks are landing in mid-priced models, and the Ecovacs Deebot T90 Pro Omni is the poster child. It delivers near-flagship mopping and automation at a price well under the top tier, which is why it remains my value pick. The Ecovacs X12 OmniCyclone is also worth a look for its bagless dock if you would rather rinse a bin than buy bags. I made no ranking changes today because nothing in the news shifts the order, the field is just getting deeper.",
   [{"title": "Dreame X60 Max Ultra is still the most consistent cleaner", "body": "It keeps the overall crown in June testing on the strength of 35,000 Pa suction, the HyperStream Duo Divide anti-tangle brush, and a slim retractable-LiDAR body. That mix delivers strong deep-carpet results and excellent flattened pet-hair pickup, which is exactly what separates a flagship from a merely good robovac."},
    {"title": "Roborock Saros 20 is the home for obstacle-heavy floors", "body": "The AdaptiLift chassis crosses raised thresholds, thick transition strips, and small inter-room steps that stop most rivals. If your layout is full of these, the Saros 20 navigates and maps its way through where others get stuck, making it the smarter pick for tricky homes."},
    {"title": "Ecovacs Deebot T90 Pro Omni is the value standout", "body": "Flagship features are moving downstream fast, and the T90 Pro Omni captures most of them, strong mopping, advanced obstacle avoidance, and a full self-empty dock, at a price well below the ultra-premium tier. It is the model I point budget-conscious buyers to this month."}],
   "進入六月，Dreame X60 Max Ultra 在我這還是穩坐第一，最新的月度測試也一直印證這個判斷。Vacuum Wars 六月還是把它選為整體最強掃地機器人，它靠的就是清潔表現比其他機型更穩定。35,000 Pa 吸力、HyperStream Duo Divide 防纏繞滾刷，加上薄型可伸縮 LiDAR 機身，深層地毯、被踩平的寵物毛、低矮家具底下，它通通自己搞定，我完全不用在旁邊顧。說真的，花旗艦價就是要買這種省心，這台週週都對得起價錢。\n\nRoborock Saros 20 守在第二，是越障專家。它的 AdaptiLift 底盤還是能跨過其他機型卡住的門檻，家裡有架高磁磚、厚過門條、房間之間有小落差的話，這台就是不會停下來的那台。老實講兩台的差別很單純，Dreame 清潔稍微好一點，Roborock 爬坡跟建圖稍微好一點，兩台都很頂。\n\n這個月真正有看頭的是中階機。滾刷拖地、進階避障、自動倒垃圾這些旗艦功能，正快速下放到中價位機型，Ecovacs Deebot T90 Pro Omni 就是最佳代表。它用遠低於頂規的價格，端出接近旗艦的拖地跟自動化，所以還是我的高 CP 值首選。想省下集塵袋錢的話，X12 OmniCyclone 的免袋集塵座也值得看。今天排名沒動，新聞沒有撼動順序的事件，純粹是這個級距越來越深。",
   [{"title": "Dreame X60 Max Ultra 還是清潔最穩的那台", "body": "六月測試它繼續抱走整體冠軍，靠的是 35,000 Pa 吸力、HyperStream Duo Divide 防纏繞滾刷，加上薄型可伸縮 LiDAR 機身。深層地毯成績強、被踩平的寵物毛也清得乾淨，這正是旗艦機跟堪用機之間的差距。"},
    {"title": "Roborock Saros 20 是門檻多的家的解答", "body": "AdaptiLift 底盤能跨過架高磁磚、厚過門條、房間小落差，這些都是讓多數對手卡住的地方。家裡地形複雜的話，Saros 20 一路導航建圖過得去，別台卻會卡關，這種格局它就是聰明選擇。"},
    {"title": "Ecovacs Deebot T90 Pro Omni 是高 CP 值代表", "body": "旗艦功能下放得很快，T90 Pro Omni 幾乎全收了，強拖地、進階避障、完整自動集塵座，價格卻遠低於頂規。這個月想精打細算的人，我都先指這台。"}])


# ---------------- Cordless Vacuums ----------------
do("best-cordless-vacuums.json",
   [{"title": "Top 10 Best Cordless Vacuums of 2026", "url": "https://vacuumwars.com/vacuum-wars-best-cordless-vacuums/", "source": "Vacuum Wars"},
    {"title": "Shark vs Dyson: Which Cordless Vacuum Brand is Better in 2026?", "url": "https://www.tasteofhome.com/article/shark-vs-dyson/", "source": "Taste of Home"},
    {"title": "The Best Cordless Stick Vacuums of 2026", "url": "https://www.techgearlab.com/topics/floor-cleaning/best-cordless-stick-vacuum", "source": "TechGearLab"}],
   "The Shark PowerDetect keeps my top spot, and the reason is the same one that put it there: it cleans like a flagship and costs hundreds less than the Dyson it competes with. In side-by-side debris testing it pulls ahead on both hard floors and carpet, the dual-roller PowerDetect head shrugs off hair tangles, and the price gap is real money you keep in your pocket. Battery life is the one place it trails the very best, but for most homes the runtime is plenty and the cleaning is what you feel day to day.\n\nDyson still owns the upper end of the order. The Gen5detect at rank 2 and the V15 Detect at rank 3 deliver the raw suction and the laser dust detection that made the brand famous, and this season Dyson swapped the old trigger for a push-button power switch that makes room-to-room cleaning far less tiring. The handle is heavier than I would like at around five pounds, but the payoff is endurance and pure cleaning muscle that nothing else quite matches.\n\nFurther down the list nothing changed and nothing needed to. The Tineco Pure One A90S and Samsung Bespoke Jet AI remain strong all-rounders, and the Levoit LVAC-200 is still the budget pick I trust, with above-average pickup and real HEPA filtration at an accessible price. The Shark-versus-Dyson debate stays the defining one in this category, and my read has not moved: buy Shark for value-leading cleaning, buy Dyson when you want the absolute most power and the longest battery. I left the rankings untouched today.",
   [{"title": "Shark PowerDetect is the value-leading cleaner", "body": "It tops the list because it out-cleans pricier rivals on both hard floors and carpet while costing hundreds less. The dual-roller PowerDetect head resists hair tangles and the debris-pickup scores are genuinely flagship level, so the only real trade-off is slightly shorter battery life."},
    {"title": "Dyson Gen5detect and V15 Detect own the power tier", "body": "Ranks 2 and 3 go to Dyson for unmatched suction and laser dust detection. The new push-button power switch replaces the old trigger and makes long cleaning sessions far easier, and while the handle is on the heavy side the battery endurance and raw muscle justify it."},
    {"title": "Levoit LVAC-200 is the budget pick worth trusting", "body": "It stays the smart entry-level choice with above-average debris pickup and genuine HEPA filtration at an accessible price. For a second vacuum or a smaller home it covers the essentials without asking you to stretch your budget."}],
   "Shark PowerDetect 在我這還是第一，理由跟當初一樣，它清潔表現像旗艦，價格卻比對位的 Dyson 便宜好幾千。實機對拚清潔垃圾，硬地板跟地毯它都領先，雙滾刷 PowerDetect 吸頭幾乎不卡頭髮，省下的價差是實實在在進你口袋的錢。電池續航是它唯一輸給頂規的地方，但對多數家庭來說續航夠用，每天有感的還是清潔力。\n\nDyson 還是穩穩握著高階這一段。第二的 Gen5detect 跟第三的 V15 Detect，帶來讓品牌成名的暴力吸力跟雷射偵塵，而且這季 Dyson 把老扳機換成了按鈕開關，整間房跑來跑去清掃時手輕鬆很多。把手大約五磅，比我想要的重，但換來的是續航跟純粹的清潔力，這點別家還真的追不太上。\n\n名單再往下都沒動，也沒必要動。Tineco Pure One A90S 跟 Samsung Bespoke Jet AI 還是很全面的好手，Levoit LVAC-200 仍是我信得過的入門選擇，清潔在水準以上又有真 HEPA 濾網，價格親民。Shark 對 Dyson 還是這個品類的主旋律，我的看法沒變，要 CP 值買 Shark，要最強吸力跟最長續航就上 Dyson。今天排名我沒動。",
   [{"title": "Shark PowerDetect 是 CP 值最高的清潔好手", "body": "它能登頂，是因為硬地板跟地毯都清得比貴上好幾千的對手乾淨。雙滾刷 PowerDetect 吸頭抗頭髮纏繞，清潔垃圾的成績是真旗艦水準，唯一要妥協的就是電池續航稍短。"},
    {"title": "Dyson Gen5detect 與 V15 Detect 穩坐暴力吸力這段", "body": "第二第三都是 Dyson，靠的是無人能敵的吸力跟雷射偵塵。新的按鈕開關取代老扳機，長時間清掃輕鬆很多，把手雖然偏重，但續航跟純粹清潔力撐得起這個重量。"},
    {"title": "Levoit LVAC-200 是值得信賴的平價選擇", "body": "它仍是聰明的入門款，清潔垃圾在水準以上，又有真 HEPA 濾網，價格親民。當第二台用或小坪數家庭，它把該做的都做到，不用你硬擠預算。"}])


# ---------------- Air Purifiers ----------------
do("best-air-purifiers.json",
   [{"title": "8 Best Air Purifiers of 2026, Tested by Our Experts", "url": "https://www.consumerreports.org/appliances/air-purifiers/best-air-purifiers-of-the-year-a1197763201/", "source": "Consumer Reports"},
    {"title": "The 4 Best Air Purifiers of 2026", "url": "https://www.rtings.com/air-purifier/reviews/best/air-purifiers", "source": "RTINGS"},
    {"title": "The best air purifiers you can buy in 2026", "url": "https://housefresh.com/best-air-purifiers-we-tested/", "source": "HouseFresh"}],
   "The IQAir HealthPro Plus stays my number one, and the reasoning is unchanged: when you want the cleanest possible air with no compromises, this is the machine. Its medical-grade HyperHEPA filtration captures ultrafine particles down well below what standard HEPA targets, and the sealed system means what goes in stays trapped. It costs a lot and the filters are not cheap, but for allergy and asthma households it is the one I recommend without hesitation.\n\nThe Coway Airmega 400S holds rank 2 as the high-coverage all-rounder, and the Blueair HealthProtect 7470i sits at 3 for its quiet, efficient HEPASilent capture. Nothing in this week's reviews disturbs the top of my order, but the more interesting movement is at the value end. Consumer Reports continues to praise the Coway Airmega ProX for large rooms, where it clears dust, pollen, and smoke strongly at both high and low speeds, and the Levoit Vital 200S remains the model I hand to most people: affordable, easy to maintain, and a genuinely strong performer on everyday dust, pollen, and pet hair.\n\nThe Levoit Core 600S keeps its place as the large-room value champion, covering spaces up to roughly 635 square feet with a high air-change rate. With wildfire-smoke season and summer pollen both ramping up, the message this month is to size the purifier to the room rather than chase a single hero model. I made no ranking changes today, the field is stable and every pick still earns its slot.",
   [{"title": "IQAir HealthPro Plus is the no-compromise choice", "body": "It keeps the top spot because its medical-grade HyperHEPA filtration captures ultrafine particles well below standard HEPA targets inside a fully sealed system. The price and filter costs are high, but for allergy and asthma households it delivers the cleanest air I can recommend."},
    {"title": "Coway Airmega ProX is the large-room standout", "body": "Consumer Reports keeps rating it among the best for big spaces because it clears dust, pollen, and smoke strongly at both high and low fan speeds. As wildfire and pollen seasons ramp up, that consistent high-coverage performance is exactly what large open rooms need."},
    {"title": "Levoit Vital 200S is the pick for most people", "body": "It stays the easy recommendation thanks to an affordable price, simple maintenance, and genuinely strong capture of everyday dust, pollen, allergens, and pet hair. For a typical bedroom or living room it covers the essentials without overspending."}],
   "IQAir HealthPro Plus 在我這還是第一，理由沒變，想要最乾淨的空氣又不想妥協，就是這台。它的醫療級 HyperHEPA 濾網能抓到遠低於一般 HEPA 標準的超細懸浮微粒，密封式結構讓吸進去的髒東西出不來。它很貴、濾網也不便宜，但對過敏跟氣喘家庭，這台我推得毫不猶豫。\n\nCoway Airmega 400S 守在第二，是大坪數全能型；Blueair HealthProtect 7470i 排第三，靠的是安靜又有效率的 HEPASilent 過濾。這週的評測沒有撼動我榜首的順序，比較有看頭的是價位較親民這端。Consumer Reports 持續稱讚 Coway Airmega ProX 適合大房間，高低風速下對灰塵、花粉、煙霧的清除都很強；Levoit Vital 200S 仍是我最常推給一般人的那台，價格親民、好保養，對日常灰塵、花粉、寵物毛的表現也真的夠強。\n\nLevoit Core 600S 守住大坪數高 CP 值冠軍，覆蓋約 635 平方英尺的空間，換氣率也高。野火煙季加上夏季花粉同時升溫，這個月的重點是按房間大小選機，不要只盯著單一神機。今天排名我沒動，整個盤面很穩，每一台都還站得住自己的位置。",
   [{"title": "IQAir HealthPro Plus 是不妥協的首選", "body": "它守住榜首，靠的是醫療級 HyperHEPA 濾網，能在全密封結構裡抓到遠低於一般 HEPA 標準的超細微粒。價格跟濾網成本都高，但對過敏跟氣喘家庭，它給的是我能推薦的最乾淨空氣。"},
    {"title": "Coway Airmega ProX 是大坪數的亮點", "body": "Consumer Reports 持續把它列為大空間最強之一，因為高低風速下對灰塵、花粉、煙霧的清除都很穩。野火季跟花粉季同時升溫，大開放空間要的就是這種穩定的大範圍表現。"},
    {"title": "Levoit Vital 200S 是最適合一般人的選擇", "body": "它仍是好推薦的那台，價格親民、保養簡單，對日常灰塵、花粉、過敏原跟寵物毛的捕捉也真的夠強。一般臥室或客廳，它把該顧的都顧到，又不用多花錢。"}])


# ---------------- Portable Air Conditioners ----------------
do("best-portable-air-conditioners.json",
   [{"title": "The best portable air conditioner in 2026, tried and tested", "url": "https://www.cnn.com/cnn-underscored/reviews/best-portable-air-conditioner", "source": "CNN Underscored"},
    {"title": "The 4 Best Portable Air Conditioners of 2026", "url": "https://www.rtings.com/air-conditioner/reviews/best/portable", "source": "RTINGS"},
    {"title": "This Is Consumer Reports' Highest-Rated Portable AC Unit In 2026", "url": "https://www.housedigest.com/2160497/highest-rated-portable-air-conditioner-unit-consumer-reports-2026/", "source": "House Digest"}],
   "With summer heat building, the Midea Duo MAP14HS1TBL stays my number one, and the reviews keep backing it. Its dual-hose inverter design cools faster and more efficiently than the single-hose crowd, it runs whisper-quiet at roughly 42 to 49 decibels, and it adds heating plus genuinely useful smart controls. That combination is why it tops multiple 2026 lists, and it is the unit I would put in a bedroom without a second thought about noise.\n\nThe Whynter NEX ARC-1230WN holds rank 2, and RTINGS still calls it the best portable AC it has tested, praising its cooling power, easy setup, and low noise. The LG LP1419IVSM sits at 3 as another strong inverter option. Nothing in this week's coverage moves my top three, they remain the units that combine real cooling output with livable sound levels.\n\nFurther down, the Hisense HAP0824TWD is worth flagging because Consumer Reports gave it the highest overall score among the units it tested, so if you want a lab-validated pick it deserves a look at rank 4. The budget end is steady too, with value-focused options from Black+Decker and others covering smaller rooms without the inverter premium. My advice this month is simple: pay for a dual-hose inverter if you can, because the efficiency and quiet operation pay you back every night during a heat wave. I left the rankings unchanged today.",
   [{"title": "Midea Duo MAP14HS1TBL is the unit to beat", "body": "Its dual-hose inverter design cools faster and more efficiently than single-hose rivals while running at a quiet 42 to 49 decibels, and it adds heating and smart controls. That blend tops multiple 2026 lists and makes it the easy bedroom choice where noise matters most."},
    {"title": "Whynter NEX ARC-1230WN is the tested-best alternative", "body": "RTINGS still rates it the best portable AC it has tested, citing strong cooling power, easy setup, and low noise. It holds rank 2 as the pick for buyers who want maximum cooling performance backed by hands-on lab testing."},
    {"title": "Hisense HAP0824TWD earns the Consumer Reports nod", "body": "It posted the highest overall score among the portable units Consumer Reports tested, which is why it sits at rank 4 as the lab-validated value option. If independent test data is what sways you, this is the model to shortlist."}],
   "夏天熱起來了，Midea Duo MAP14HS1TBL 在我這還是第一，評測也一直挺它。雙軟管變頻設計，降溫比單管那群快又省電，運轉只有大約 42 到 49 分貝、安靜得很，還多了暖氣跟真的好用的智慧控制。這套組合就是它登上多個 2026 榜單的原因，要放臥室我完全不會擔心吵。\n\nWhynter NEX ARC-1230WN 守在第二，RTINGS 還是說它是測過最強的移動式冷氣，稱讚它的降溫力、好安裝、低噪音。LG LP1419IVSM 排第三，是另一台強力變頻選擇。這週的報導沒有動到我的前三名，它們依舊是降溫實力跟可接受音量兼顧的機型。\n\n再往下，Hisense HAP0824TWD 值得點名，Consumer Reports 給它測試機型裡最高的總分，想要實驗室背書的選擇，第四名這台值得看。平價這端也很穩，Black+Decker 之類主打 CP 值的款式，能搞定小房間又不用付變頻溢價。這個月我的建議很簡單，預算夠就上雙軟管變頻，熱浪來的每個晚上，省電跟安靜都會回報你。今天排名我沒動。",
   [{"title": "Midea Duo MAP14HS1TBL 是要被超越的標竿", "body": "雙軟管變頻設計降溫比單管對手快又省電，運轉只有 42 到 49 分貝、很安靜，還多了暖氣跟智慧控制。這個組合登上多個 2026 榜單，最在意吵不吵的臥室，它就是輕鬆首選。"},
    {"title": "Whynter NEX ARC-1230WN 是測試最強的替代選擇", "body": "RTINGS 還是把它評為測過最強的移動式冷氣，稱讚降溫力強、好安裝、低噪音。它守在第二，是想要最強降溫又要實機測試背書的人的選擇。"},
    {"title": "Hisense HAP0824TWD 拿下 Consumer Reports 認證", "body": "在 Consumer Reports 測試的移動式機型裡，它拿下最高總分，所以排在第四，是有實驗室背書的 CP 值選擇。如果獨立測試數據能說服你，這台值得列入口袋名單。"}])


# ---------------- Smart Thermostats ----------------
do("best-smart-thermostats.json",
   [{"title": "Best Smart Thermostats 2026: Ecobee, Nest, Honeywell Ranked", "url": "https://www.smarthomeexplorer.com/guides/best-smart-thermostats-hub-2026", "source": "Smart Home Explorer"},
    {"title": "Ecobee and Nest lead 2026 smart thermostat rankings", "url": "https://www.msn.com/en-us/news/other/ecobee-and-nest-lead-2026-smart-thermostat-rankings/gm-GM9F89B1BC", "source": "MSN"},
    {"title": "10 Best Smart Thermostats of 2026", "url": "https://www.reviewed.com/smarthome/best-right-now/the-best-smart-thermostats", "source": "Reviewed"}],
   "The Ecobee Smart Thermostat Premium keeps my top spot, and the latest 2026 rankings agree. What earns it the win is completeness: it ships with a SmartSensor that genuinely fixes uneven heating and cooling between rooms, it monitors air quality on the device, and it works with Alexa, Google, Siri, and HomeKit, the broadest platform support in the category. At an MSRP of about $250 with promo lows near $200, it is priced like the premium pick it is, and the included sensor makes that money back in comfort.\n\nThe Google Nest Learning Thermostat 4th Gen holds rank 2 and is the smarter buy for Google Home households. This generation brings a better display, a faster processor, and the addition of Apple Home support, and its learning algorithm still builds a schedule from your first week of manual adjustments. If your routine is consistent it handles scheduling on its own, and it usually runs $50 to $80 cheaper than the comparable Ecobee.\n\nOne thing I want buyers to keep grounded is the savings claim. Manufacturers cite figures up to 26 percent, but independent ENERGY STAR data points to around 8 percent on annual heating and cooling, roughly $50 to $100 for a typical home. That is still real money, and either of my top two will deliver it. The Honeywell Home T9 stays at rank 3 as the value-minded multi-sensor option. I made no ranking changes today, the leaders are clear and the order holds.",
   [{"title": "Ecobee Smart Thermostat Premium is the most complete", "body": "It keeps the crown thanks to an included SmartSensor that fixes uneven room temperatures, on-device air-quality monitoring, and support for Alexa, Google, Siri, and HomeKit. At around $250 list with promo lows near $200, the bundled sensor turns a premium price into real everyday comfort."},
    {"title": "Google Nest Learning Thermostat 4th Gen is the Google-home value play", "body": "Rank 2 goes to Nest for a better display, faster processor, and new Apple Home support, plus a learning algorithm that builds your schedule from a week of manual tweaks. It typically runs $50 to $80 less than the comparable Ecobee, which makes it the smart pick in a Google ecosystem."},
    {"title": "Keep the savings expectation realistic", "body": "Manufacturers cite up to 26 percent, but independent ENERGY STAR data shows roughly 8 percent off annual heating and cooling, about $50 to $100 for a typical home. That is still worthwhile, and both top picks deliver it while paying you back through comfort and automation."}],
   "Ecobee Smart Thermostat Premium 在我這還是第一，最新的 2026 排名也認同。它能贏靠的是完整度，盒裝就附 SmartSensor，能真的解決房間之間冷熱不均的問題，機身還能偵測空氣品質，並且同時支援 Alexa、Google、Siri 跟 HomeKit，平台支援是這個品類最廣的。建議售價大約台幣七千多，特價時逼近六千出頭，定位就是高階機該有的價格，附的感測器會用舒適度把錢賺回來。\n\nGoogle Nest Learning Thermostat 4th Gen 守在第二，是 Google Home 家庭更聰明的選擇。這代帶來更好的螢幕、更快的處理器，還新增了 Apple Home 支援，學習演算法依舊會從你第一週的手動調整建立排程。作息固定的話它會自己排好，而且通常比同級 Ecobee 便宜台幣一千五到兩千五。\n\n有件事我想提醒大家別被沖昏頭，就是省電的數字。廠商喊到 26%，但獨立的 ENERGY STAR 數據顯示，一年冷暖氣大約省 8%，一般家庭差不多是台幣一千五到三千。這還是實實在在的錢，我前兩名任一台都辦得到。Honeywell Home T9 守在第三，是重視 CP 值的多感測器選擇。今天排名我沒動，領先群很清楚，順序也站得住。",
   [{"title": "Ecobee Smart Thermostat Premium 完整度最高", "body": "它守住冠軍，靠的是盒裝附的 SmartSensor 解決房間溫差、機身空氣品質偵測，加上同時支援 Alexa、Google、Siri 跟 HomeKit。售價約台幣七千多、特價逼近六千出頭，附的感測器把高階價格換成每天有感的舒適。"},
    {"title": "Google Nest Learning Thermostat 4th Gen 是 Google 家庭的 CP 值之選", "body": "第二名給 Nest，這代螢幕更好、處理器更快、新增 Apple Home 支援，學習演算法會從一週的手動調整建立排程。通常比同級 Ecobee 便宜台幣一千五到兩千五，在 Google 生態系裡就是聰明選擇。"},
    {"title": "省電期待要放實際一點", "body": "廠商喊到 26%，但獨立的 ENERGY STAR 數據顯示一年冷暖氣大約省 8%，一般家庭約台幣一千五到三千。這還是值得，前兩名都辦得到，還會用舒適度跟自動化把錢賺回來。"}])


# ---------------- Robot Lawn Mowers ----------------
do("best-robot-lawn-mowers.json",
   [{"title": "Best Robot Lawn Mower 2026 (Tested & Reviewed for U.S. Lawns)", "url": "https://us.mammotion.com/blogs/news/best-robot-lawn-mower-2026", "source": "Mammotion"},
    {"title": "9 Best Robot Lawn Mowers of 2026", "url": "https://www.reviewed.com/home-outdoors/best-right-now/best-robot-lawn-mowers", "source": "Reviewed"},
    {"title": "Best robotic lawn mowers to buy in 2026", "url": "https://www.gardenersworld.com/reviews/lawn-care/best-robotic-mowers/", "source": "BBC Gardeners' World"}],
   "The Mammotion LUBA 3 AWD 5000 stays my number one for the 2026 season, and with mowing in full swing it keeps proving the call. It strikes the best balance of precision navigation, terrain adaptability, and full automation for mid to large lawns. The mix of RTK GPS, LiDAR scanning, and AI vision keeps it on line without boundary wires, and the all-wheel-drive system gives it real traction on slopes up to 80 percent. If your yard is hilly or irregular, that AWD grip is the difference between a mower that finishes and one that gets stuck.\n\nThe Ecovacs Goat A3000 LiDAR Pro holds rank 2. It is essentially the proven A3000 with the new TruEdge edge trimmer, which improves how cleanly it finishes borders, a frequent weak point for robot mowers. The original A3000 LiDAR sits right behind at 3 and remains a strong buy if you find it discounted now that the Pro is out.\n\nThe broader story this season is access. Wire-free RTK navigation is now landing under $1500, and LiDAR systems are delivering centimeter-level precision that used to demand buried boundary wires and hours of setup. That is genuinely changing who can own one of these. The Navimow X315 and i2 LiDAR keep their mid-pack spots as solid wire-free options. My guidance stays the same: match the navigation tech and slope rating to your actual yard. I made no ranking changes today.",
   [{"title": "Mammotion LUBA 3 AWD 5000 is the all-terrain leader", "body": "It holds the top spot by balancing precision navigation, terrain adaptability, and full automation for mid to large lawns. RTK GPS, LiDAR, and AI vision keep it wire-free and on line, while the all-wheel-drive system grips slopes up to 80 percent, the feature that lets it finish hilly and irregular yards."},
    {"title": "Ecovacs Goat A3000 LiDAR Pro sharpens the edges", "body": "Rank 2 goes to the Pro because it adds the new TruEdge edge trimmer to the proven A3000 platform, cleaning up border finishing that trips up many robot mowers. The original A3000 LiDAR sits just behind and is a smart buy if you catch it discounted."},
    {"title": "Wire-free RTK is now genuinely affordable", "body": "This season pushes wire-free RTK navigation under $1500 and brings centimeter-level LiDAR precision to setups that once needed buried boundary wires and hours of work. That shift widens who can realistically own a robot mower, with the Navimow X315 and i2 LiDAR holding solid mid-pack value."}],
   "Mammotion LUBA 3 AWD 5000 在我這還是 2026 球季的第一，割草旺季開打，它一直在印證這個選擇。中大型草坪要的精準導航、地形適應、完整自動化，它平衡得最好。RTK GPS、LiDAR 掃描加上 AI 視覺，免埋邊界線就能走得很正，四輪驅動在最高 80% 的坡度上還有真抓地力。院子有坡、形狀不規則的話，這套 AWD 抓地就是割得完跟卡住的差別。\n\nEcovacs Goat A3000 LiDAR Pro 守在第二。它基本上就是已驗證的 A3000，加上新的 TruEdge 修邊器，把邊界收得更乾淨，而邊界正是割草機器人常見的弱點。原版 A3000 LiDAR 緊跟在第三，Pro 出了之後如果原版有折扣，還是很值得入手。\n\n這季更大的故事是門檻。免線 RTK 導航現在已經下殺到台幣四萬五以內，LiDAR 系統提供的公分級精度，以前可是要埋邊界線、花好幾個小時設定才有的。這真的改變了誰買得起這類產品。Navimow X315 跟 i2 LiDAR 守住中段，是穩健的免線選擇。我的建議沒變，導航技術跟坡度規格要對上你家草坪的實際狀況。今天排名我沒動。",
   [{"title": "Mammotion LUBA 3 AWD 5000 是全地形王者", "body": "它守住第一，靠的是中大型草坪要的精準導航、地形適應、完整自動化全都平衡得好。RTK GPS、LiDAR、AI 視覺讓它免線又走得正，四輪驅動在最高 80% 坡度上抓得住，這正是它能割完有坡、不規則院子的關鍵。"},
    {"title": "Ecovacs Goat A3000 LiDAR Pro 把邊界收得更利", "body": "第二名給 Pro，因為它在已驗證的 A3000 平台上加了新的 TruEdge 修邊器，把多數割草機器人都搞不定的邊界收乾淨。原版 A3000 LiDAR 緊跟在後，原版有折扣的話是聰明選擇。"},
    {"title": "免線 RTK 現在真的買得起了", "body": "這季把免線 RTK 導航壓到台幣四萬五以內，還帶來以前要埋邊界線、花好幾小時才有的公分級 LiDAR 精度。這個轉變讓更多人實際買得起割草機器人，Navimow X315 跟 i2 LiDAR 守住中段穩健 CP 值。"}])


# ---------------- Robotic Pool Cleaners ----------------
do("best-robotic-pool-cleaners.json",
   [{"title": "Best Robotic Pool Cleaners of 2026. Over 30+ Tested & Reviewed.", "url": "https://www.thepoolnerd.com/best-robotic-pool-cleaners", "source": "The Pool Nerd"},
    {"title": "Best robotic pool cleaners 2026: Big, small, and cordless options", "url": "https://www.pcworld.com/article/2266557/best-robot-pool-cleaners.html", "source": "PCWorld"},
    {"title": "The Best Robotic Pool Cleaners for 2026, Tested and Reviewed", "url": "https://www.poolbots.com/best-robotic-pool-cleaners", "source": "Poolbots"}],
   "With pool season open, the Dolphin Premier stays my number one. After more than thirty units tested across the field, it is still the most complete cleaner you can buy, with commercial-grade dual motors, multi-media filtration including a NanoFilter option, waterline scrubbing, a weekly smart timer, and a three-year warranty that is rare in this category. It is corded, and that is a feature, not a flaw, because the constant power means stronger suction and true set-and-forget automation.\n\nThat corded-versus-cordless point is the theme I keep coming back to this season. The reviews are blunt: experts broadly advise against cordless models in 2026 because corded cleaners win on suction, filtration, and true scheduling, with none of the lithium-battery fire risk. Cordless units still need daily recharging, carry smaller motors, and run only two to three hours before a long recharge. That is why my corded picks hold the top of the order.\n\nThat said, the Beatbot AquaSense 2 Ultra stays at rank 2 because it is the cordless model that comes closest to closing the gap, with strong multi-surface cleaning and smart navigation for owners who simply will not deal with a cord. The Dolphin Nautilus CC Plus WiFi at rank 3 remains the value-corded workhorse I recommend most. My advice this month is straightforward: if you want the best clean and the least fuss, buy corded. I made no ranking changes today.",
   [{"title": "Dolphin Premier is the most complete cleaner", "body": "After 30-plus units tested it keeps the top spot with commercial-grade dual motors, multi-media filtration including a NanoFilter, waterline scrubbing, a weekly smart timer, and a rare three-year warranty. Being corded is a strength here, the constant power drives stronger suction and genuine set-and-forget automation."},
    {"title": "Corded still wins on performance and safety in 2026", "body": "Reviewers broadly advise against cordless this season because corded cleaners lead on suction, filtration, and true scheduling while carrying no lithium-battery fire risk. Cordless units need daily recharging, use smaller motors, and run only two to three hours, which is why the corded picks hold the top of the order."},
    {"title": "Beatbot AquaSense 2 Ultra is the best cordless option", "body": "It holds rank 2 as the cordless model that comes closest to matching corded performance, with strong multi-surface cleaning and smart navigation. For owners who refuse to manage a cord, it is the one cordless cleaner worth the trade-offs this season."}],
   "泳池季開了，Dolphin Premier 在我這還是第一。測過三十多台之後，它仍是你買得到最完整的清潔機，商規雙馬達、含 NanoFilter 選項的多介質過濾、水線刷洗、每週智慧定時，還有這個品類少見的三年保固。它是有線的，而這是優點不是缺點，因為持續供電代表更強的吸力跟真正的設定完就不用管的自動化。\n\n有線對無線這件事，是我這季一直回頭講的主題。評測講得很直白，2026 年專家普遍不建議買無線機型，因為有線機在吸力、過濾、真排程上都贏，又沒有鋰電池的起火風險。無線機還是要天天充電、馬達較小，跑兩到三小時就得長時間回充。這就是為什麼我的有線選擇守在榜首。\n\n話說回來，Beatbot AquaSense 2 Ultra 守在第二，因為它是最接近追平差距的無線機型，多表面清潔力強、智慧導航也好，適合就是不想處理電線的人。第三名 Dolphin Nautilus CC Plus WiFi 仍是我最常推的有線 CP 值主力。這個月我的建議很直接，想要最乾淨又最省心，就買有線。今天排名我沒動。",
   [{"title": "Dolphin Premier 是最完整的清潔機", "body": "測過三十多台後它守住第一，商規雙馬達、含 NanoFilter 的多介質過濾、水線刷洗、每週智慧定時，還有少見的三年保固。有線在這裡是優勢，持續供電帶來更強吸力跟真正設定完就不用管的自動化。"},
    {"title": "2026 年有線在表現跟安全上還是贏", "body": "評測這季普遍不建議買無線，因為有線機在吸力、過濾、真排程上領先，又沒有鋰電池起火風險。無線機要天天充電、馬達較小、只能跑兩到三小時，這就是有線選擇守在榜首的原因。"},
    {"title": "Beatbot AquaSense 2 Ultra 是最好的無線選擇", "body": "它守在第二，是最接近追平有線表現的無線機型，多表面清潔力強、智慧導航也好。對就是不想處理電線的人來說，這季值得接受那些取捨的無線機就是它。"}])

print("ALL DONE")
