import sys
sys.path.insert(0, "/Users/etrexkuo/toprankland/scripts")
from daily_helper import load, save, upsert, last_rankings
DATE = "2026-06-03"


def do(fname, references, en_comm, en_hl, zh_comm, zh_hl):
    d, p = load(fname)
    entry = {"date": DATE, "rankings": last_rankings(d), "references": references,
             "i18n": {"en": {"commentary": en_comm, "highlights": en_hl},
                      "zh-tw": {"commentary": zh_comm, "highlights": zh_hl}}}
    upsert(d, entry); save(p, d); print("OK", fname)


# ---------------- AI CHATBOTS ----------------
do("best-ai-chatbots.json",
   [{"title": "Best AI Models in 2026: GPT-5.5 vs Claude vs Gemini", "url": "https://medium.com/@sanjeevpatel3007/best-ai-models-in-2026-the-complete-honest-ranking-d67b63cf3543", "source": "Medium"},
    {"title": "AI Chatbots Comparison: ChatGPT, Claude, Meta AI, Gemini and more", "url": "https://artificialanalysis.ai/agents/chatbots", "source": "Artificial Analysis"},
    {"title": "AI Model Leaderboard June 2026 — LMSys Arena, LLM, Image & Coding Rankings", "url": "https://www.swfte.com/ai/leaderboard", "source": "Swfte"}],
   "The intelligence race tightened again this week. Artificial Analysis now has Claude Opus 4.8 on top of its Intelligence Index at 61.4, narrowly ahead of GPT-5.5 at 60.2, Gemini 3.1 Pro at 57, and Grok 4.3 at 53. That tells me the labs are clustering at the frontier, and the gaps that matter to everyday users are getting smaller every month. So why do I still keep ChatGPT at number one here. Because this ranking is about the chatbot you actually live in, not just the raw model behind it. ChatGPT keeps the broadest consumer ecosystem, the most polished mobile app, and the deepest set of integrations, and GPT-5.5 sits comfortably at the top of creative writing where it has led since GPT-5.1. Claude stays at number two and earns it on substance. Opus 4.8 posts 88.6 percent on SWE-bench Verified, a number no rival is close to, so if your day is writing and reasoning about code, Claude is the chat window I trust most. Gemini holds third because Gemini 3.1 Pro leads reasoning and data analysis while plugging straight into Google's apps, which is enormous reach. I left every rank and score unchanged this week. None of the news represents a market shift, just steady benchmark jockeying, and I refuse to shuffle a leaderboard on noise. Grok 4.3 stays the value-minded pick of the four flagships with strong agentic scores at the lowest price. The honest read for June is that the top three are all excellent, and your choice should follow your workflow rather than a single index number.",
   [{"title": "ChatGPT still leads on reach", "body": "ChatGPT holds number one on the strength of ecosystem and polish, not a single benchmark. GPT-5.5 tops creative writing and the app remains the default for hundreds of millions of casual users, which is exactly what a consumer chatbot ranking should reward."},
    {"title": "Claude owns the coding chair", "body": "Claude stays second because Opus 4.8 posts 88.6 percent on SWE-bench Verified, well ahead of GPT-5.5 and Gemini 3.1 Pro. If your conversations are mostly about building software, Claude is the window that gets the details right."},
    {"title": "The frontier is clustering", "body": "Claude Opus 4.8 at 61.4 and GPT-5.5 at 60.2 on the Artificial Analysis index show the gaps shrinking. I held all ranks and scores this week because steady benchmark jockeying is not a reason to reshuffle a leaderboard."}],
   "這禮拜智慧競賽又更貼近了。Artificial Analysis 的智慧指數現在把 Claude Opus 4.8 排第一拿到 61.4，小幅領先 GPT-5.5 的 60.2，再來是 Gemini 3.1 Pro 的 57 跟 Grok 4.3 的 53。說真的，這代表幾家大廠在頂端越擠越近，對一般使用者有感的差距其實一個月比一個月小。那我幹嘛還把 ChatGPT 擺第一。因為這份榜單比的是你每天真的在用的那個聊天視窗，不是只看背後模型的裸分。ChatGPT 的消費端生態最廣，手機 App 最順，整合最深，而且 GPT-5.5 在創意寫作這塊從 GPT-5.1 就一路領先到現在。Claude 穩坐第二，靠的是真功夫，Opus 4.8 在 SWE-bench Verified 拿到 88.6 趴，這個數字沒人追得上，所以你一整天都在跟程式碼打交道的話，Claude 就是我最信的那個視窗。Gemini 排第三也合理，Gemini 3.1 Pro 在推理跟資料分析最強，又能直接接進 Google 全家桶，觸及量超大。這週我把所有名次跟分數都維持不動。這些新聞沒有一個構成市場轉向，純粹是跑分你來我往，我才不會為了雜訊去動榜單。Grok 4.3 還是四款旗艦裡最會精打細算的那個，代理能力強、價格又最低。六月的老實話就是，前三名都很猛，挑哪個應該看你的工作流，別只盯著一個指數。",
   [{"title": "ChatGPT 贏在觸及面", "body": "ChatGPT 排第一靠的是生態跟順手度，不是單一跑分。GPT-5.5 在創意寫作稱霸，App 又是好幾億輕度使用者的預設選擇，這正是消費級聊天榜單該獎勵的東西。"},
    {"title": "Claude 守住寫程式那把交椅", "body": "Claude 穩坐第二，因為 Opus 4.8 在 SWE-bench Verified 拿 88.6 趴，明顯把 GPT-5.5 跟 Gemini 3.1 Pro 拋在後面。你的對話大多在蓋軟體的話，Claude 就是最會抓細節的那個視窗。"},
    {"title": "頂端越擠越近", "body": "Claude Opus 4.8 的 61.4 跟 GPT-5.5 的 60.2 在 Artificial Analysis 指數上看，差距正在縮小。這週我把名次跟分數全留著，跑分你來我往不是重排榜單的理由。"}])


# ---------------- AI CODING ASSISTANTS ----------------
do("best-ai-coding-assistants.json",
   [{"title": "Best AI Coding Assistants 2026 (I Tested 10+)", "url": "https://playcode.io/blog/best-ai-coding-assistants-2026", "source": "Playcode Blog"},
    {"title": "Best AI Coding Tools 2026: Complete Ranking by Real-World Performance", "url": "https://www.nxcode.io/resources/news/best-ai-for-coding-2026-complete-ranking", "source": "NxCode"},
    {"title": "Best AI Code Assistants Reviews 2026", "url": "https://www.gartner.com/reviews/market/ai-code-assistants", "source": "Gartner Peer Insights"}],
   "The big news this week is structural, not about a new model. On June 1 every GitHub Copilot plan moved to usage-based billing through GitHub AI Credits, one credit equal to one cent, priced by model and token consumption. For heavy users that changes the math, and I think it nudges some teams toward Claude Code and Cursor where the cost story is more predictable. I am keeping Claude Code at number one. It pairs the strongest coding model in the market, Opus 4.8 at 88.6 percent on SWE-bench Verified, with a real agentic CLI, a million-token context, and deep git integration. When I hand it a messy multi-file refactor it actually finishes the job, and that is the bar that matters. Cursor stays second because it is still the best AI-native IDE, with visual diffs and autocomplete woven into every keystroke, and it remains the default editor for people running Claude as their backend. Codex sits third on the back of GPT-5.5's strong agentic coding, and it is the cleanest fit if you live in VS Code or JetBrains and want OpenAI's own agent. GitHub Copilot holds its spot as the industry standard despite the billing shift, because the editor integration and reach are still unmatched. I left the full ranking unchanged this week. The Copilot pricing change is worth flagging loudly, but it does not move the quality order, so the list stands.",
   [{"title": "Claude Code stays the agent to beat", "body": "Number one holds because Opus 4.8 leads SWE-bench Verified at 88.6 percent and the CLI actually completes large multi-file refactors with git integration and a million-token context. That combination of model plus harness is what keeps it ahead."},
    {"title": "Copilot's June billing shift matters", "body": "On June 1 all Copilot plans moved to usage-based GitHub AI Credits at one cent each. Heavy users should re-run their cost math, since predictable pricing is part of why Claude Code and Cursor look attractive right now."},
    {"title": "Cursor and Codex round out the top tier", "body": "Cursor stays second as the best AI-native IDE with visual diffs woven into every keystroke. Codex holds third on GPT-5.5's agentic coding strength, the cleanest pick for VS Code and JetBrains users wanting OpenAI's own agent."}],
   "這週的大新聞是結構性的，不是又出了什麼新模型。六月一號起，所有 GitHub Copilot 方案都改成用量計費，走 GitHub AI Credits，一點等於一美分，依模型跟 token 用量收錢。對重度使用者來說這帳要重算了，老實講我覺得這會把一些團隊推向 Claude Code 跟 Cursor，因為那邊的成本比較好抓。我繼續把 Claude Code 放第一。它把市場最強的編碼模型 Opus 4.8（SWE-bench Verified 88.6 趴）配上真正能跑的代理 CLI、百萬 token 上下文跟深度 git 整合。我丟一個亂七八糟的跨檔案重構給它，它真的會把活幹完，這才是重點。Cursor 守第二，因為它還是最好的 AI 原生 IDE，視覺化 diff 跟自動補全融進每一次敲鍵，而且拿 Claude 當後端的人幾乎都用它。Codex 排第三，靠 GPT-5.5 的代理編碼實力，你整天泡在 VS Code 或 JetBrains 又想用 OpenAI 自家代理的話，它最對味。GitHub Copilot 雖然改了計費，還是守住業界標準的位子，編輯器整合跟觸及面就是無人能比。這週整份名次我維持不動。Copilot 改價值得大聲提醒，但它沒撼動品質排序，所以榜單照舊。",
   [{"title": "Claude Code 還是那個要被挑戰的代理", "body": "第一名守住，因為 Opus 4.8 在 SWE-bench Verified 以 88.6 趴領先，而且 CLI 真的能把大型跨檔案重構幹完，還有 git 整合跟百萬 token 上下文。模型加上工具鏈這組合就是它領先的原因。"},
    {"title": "Copilot 六月改價有感", "body": "六月一號起所有 Copilot 方案改成用量制的 GitHub AI Credits，一點一美分。重度使用者該重算成本了，畢竟價格好抓正是 Claude Code 跟 Cursor 現在看起來吸引人的一部分。"},
    {"title": "Cursor 跟 Codex 撐起第一梯隊", "body": "Cursor 守第二，最好的 AI 原生 IDE，視覺化 diff 融進每一次敲鍵。Codex 靠 GPT-5.5 的代理編碼實力排第三，對泡在 VS Code 跟 JetBrains 又想用 OpenAI 自家代理的人最對味。"}])


# ---------------- AI IMAGE GENERATORS ----------------
do("best-ai-image-generators.json",
   [{"title": "Midjourney V8 vs FLUX vs Stable Diffusion: Best AI Image Generator in 2026", "url": "https://wavespeed.ai/blog/posts/midjourney-v8-vs-flux-vs-sora-best-ai-image-generator-2026/", "source": "WaveSpeed Blog"},
    {"title": "Best AI Image Generators June 2026 — Midjourney, Flux, DALL-E Compared", "url": "https://aiflashreport.com/ai-image-generators.html", "source": "AI Flash Report"},
    {"title": "AI Image Generation 2026: Midjourney v8 vs GPT Image 2 vs Flux", "url": "https://lushbinary.com/blog/ai-image-generation-comparison-midjourney-gpt-flux/", "source": "Lushbinary"}],
   "The story I keep seeing in June is fragmentation, and I think that is healthy. There is no single best image model anymore, the market has split by job. Midjourney v8 leads on pure aesthetics, GPT Image 2 leads on prompt accuracy, and Flux 2 Pro leads on photorealism. That is exactly how my rankings are weighted, so the order holds this week with no changes. I keep Midjourney v8 at number one because when the brief is beauty and you are art-directing by hand, nothing interprets a mood like it does. The v8 Alpha that landed in March added 2K native resolution and roughly 5x faster generation over v7, plus moodboards and stronger style references, and that pipeline is a joy for visual development. Flux 2 Pro stays my photorealism pick, the model where skin renders with real pores and translucency, fabric drapes with weight, and glass refracts correctly, so it is my default when an image has to pass as an actual photograph. GPT Image 2 holds for prompt obedience, the one I reach for when the exact words on a sign or the precise layout matter more than painterly flair. Imagen 4 and Firefly 4 keep their slots for Google-stack and commercially-safe Adobe workflows respectively. I made no rank or score moves this week. The releases are incremental and the specialization map is stable, so the list reflects reality.",
   [{"title": "Midjourney v8 owns aesthetics", "body": "Number one holds because the v8 Alpha added 2K native resolution and around 5x faster generation over v7, plus moodboards and stronger style references. When you are art-directing for beauty by hand, nothing interprets a mood as well."},
    {"title": "Flux 2 Pro is the photorealism default", "body": "Skin renders with real pores and translucency, fabric drapes with believable weight, and glass refracts correctly. When an image has to pass as an actual photograph, Flux 2 Pro is the model I reach for first."},
    {"title": "The market is specialized, not winner-take-all", "body": "Midjourney v8 leads aesthetics, GPT Image 2 leads prompt accuracy, Flux 2 Pro leads photorealism. That split is stable this week, so I held every rank and score rather than chase incremental releases."}],
   "六月我一直看到的主軸就是分眾，而且我覺得這是好事。現在沒有單一最強的圖像模型了，市場按用途切開了。Midjourney v8 純美感最強，GPT Image 2 提示詞還原最準，Flux 2 Pro 寫實度最高。我的榜單權重正是這樣分的，所以這週排序維持不動。我把 Midjourney v8 留在第一，因為當案子要的是美、你又在手動指導美術時，沒人比它更會抓氛圍。三月落地的 v8 Alpha 加了 2K 原生解析度、比 v7 快約五倍，還有情緒板跟更強的風格參考，這條流程做視覺開發真的很爽。Flux 2 Pro 還是我的寫實首選，皮膚有真實毛孔跟透光感，布料垂墜有重量，玻璃折射也對，所以圖要能被當成真照片時我預設用它。GPT Image 2 守住提示詞服從度，招牌上的字要精準、版面要照排時我就找它，不是看它畫得多有韻味。Imagen 4 跟 Firefly 4 各守 Google 生態跟 Adobe 商用安全那塊。這週名次跟分數都沒動。更新都是小幅，分工地圖也穩，榜單就如實反映現況。",
   [{"title": "Midjourney v8 美感稱王", "body": "第一名守住，因為 v8 Alpha 加了 2K 原生解析度、比 v7 快約五倍，還有情緒板跟更強風格參考。你手動指導美術追求美感時，沒人比它更會抓氛圍。"},
    {"title": "Flux 2 Pro 是寫實預設", "body": "皮膚有真實毛孔跟透光感，布料垂墜有重量，玻璃折射也對。圖要能被當成真照片時，Flux 2 Pro 就是我第一個拿出來的模型。"},
    {"title": "市場是分眾，不是贏者全拿", "body": "Midjourney v8 美感最強，GPT Image 2 提示詞最準，Flux 2 Pro 寫實最高。這個分工這週很穩，所以我把名次跟分數全留著，不去追小幅更新。"}])


# ---------------- AI MEETING ASSISTANTS ----------------
do("best-ai-meeting-assistants.json",
   [{"title": "The 10 best AI meeting assistants in 2026", "url": "https://zapier.com/blog/best-ai-meeting-assistant/", "source": "Zapier"},
    {"title": "Granola vs Otter vs Fathom: Which AI Note Taker Wins in 2026?", "url": "https://www.itsconvo.com/blog/granola-vs-otter-vs-fathom", "source": "Convo"},
    {"title": "7 AI Meeting Notetakers Tested in 2026 (Fathom vs Fireflies vs Otter)", "url": "https://get-alfred.ai/blog/best-ai-meeting-notetakers", "source": "Alfred"}],
   "The defining question in this category for June is still bot or no bot, and that fault line is shaping every review I read. I keep Granola at number one because it nails the bot-free model, capturing audio straight from your device with no visible bot joining the call, then enhancing the notes you take by hand with AI context from the transcript. For internal and client meetings where a Granola is joining banner would be awkward, that quiet approach is exactly right, and it is why I still trust it as the daily driver. Fathom stays second and remains the best free option in 2026, ideal for individuals and small teams who want reliable transcription and summaries without paying, and it has been pushing its own bot-less mode to chase Granola. Fireflies holds third on breadth, over a hundred languages, a deep integration ecosystem, and the AskFred assistant that queries your entire meeting archive, which makes it the pick for high-volume teams with years of recordings to search. Otter keeps fourth as the familiar all-rounder. I left the full ranking unchanged this week. There was no funding event or feature drop big enough to reorder the list, just continued convergence on bot-free recording, so the order reflects how these tools actually feel in daily use.",
   [{"title": "Granola wins on the quiet model", "body": "Number one holds because Granola captures audio from your device with no visible bot joining, then enriches your handwritten notes with transcript context. For client and internal calls where a bot banner is awkward, that is exactly the right approach."},
    {"title": "Fathom is the best free pick", "body": "Fathom stays second as the strongest free AI note taker in 2026, reliable transcription and summaries at no cost, and it has added its own bot-less mode to chase Granola directly. That makes it the obvious starting point for individuals and small teams."},
    {"title": "Fireflies wins on archive search", "body": "Fireflies holds third on breadth, over a hundred languages, a deep integration ecosystem, and the AskFred assistant that queries your entire meeting history. For high-volume teams with years of recordings, that searchable archive is the differentiator."}],
   "六月這個類別最關鍵的問題還是有沒有機器人進會議，這條分界線左右了我看到的每篇評測。我把 Granola 留第一，因為它把無機器人模式做到位，直接從你的裝置抓音訊，不會有看得到的機器人加進通話，再用逐字稿的 AI 脈絡補強你手打的筆記。內部會議或跟客戶開會時，那種 Granola 正在加入 的提示很尷尬，它這種安靜做法剛剛好，這也是我把它當主力的原因。Fathom 守第二，還是 2026 最好的免費選擇，個人跟小團隊想要可靠的逐字稿跟摘要又不想花錢就選它，而且它也推了自己的無機器人模式來追 Granola。Fireflies 排第三靠的是廣度，破百種語言、深度整合生態，加上能搜尋你整個會議檔案庫的 AskFred 助理，所以它是有好幾年錄音要翻的高頻團隊的菜。Otter 守第四，熟面孔的全能型。這週整份名次我沒動。沒有大到能重排榜單的募資或新功能，就只是大家持續往無機器人錄音靠攏，所以排序如實反映這些工具每天用起來的感覺。",
   [{"title": "Granola 靠安靜模式取勝", "body": "第一名守住，因為 Granola 從你的裝置抓音訊，不會有看得到的機器人加進來，再用逐字稿脈絡補強你手打的筆記。跟客戶或內部開會時機器人提示很尷尬，這做法剛好對味。"},
    {"title": "Fathom 是最強免費選擇", "body": "Fathom 守第二，2026 最強的免費 AI 筆記工具，可靠的逐字稿跟摘要不用錢，還加了自己的無機器人模式直追 Granola。個人跟小團隊就從它開始最合理。"},
    {"title": "Fireflies 贏在檔案庫搜尋", "body": "Fireflies 排第三靠廣度，破百種語言、深度整合生態，加上能搜你整個會議歷史的 AskFred 助理。對有好幾年錄音要翻的高頻團隊，那個可搜尋檔案庫就是差異所在。"}])


# ---------------- AI MUSIC GENERATORS ----------------
do("best-ai-music-generators.json",
   [{"title": "Best AI Music Generators in 2026: Suno vs Udio vs ElevenLabs", "url": "https://jam.com/resources/best-ai-music-generators-2026", "source": "Jam"},
    {"title": "Best AI Music Models 2026: Suno v5 vs ElevenLabs", "url": "https://www.teamday.ai/blog/best-ai-music-models-2026", "source": "TeamDay.ai"},
    {"title": "Suno vs Udio vs ElevenLabs Music: The 2026 AI Music Generator Showdown", "url": "https://www.aimagicx.com/blog/suno-vs-udio-vs-elevenlabs-music-comparison-2026", "source": "AI Magicx"}],
   "Suno v5 is still the quality benchmark, and the numbers back the gut feeling. It holds an ELO around 1,293, ahead of every competitor on audio fidelity, musical structure, and vocal realism, so it keeps number one with no hesitation from me. What makes it the daily tool is the depth around the model, Suno Studio gives you a DAW-like workspace, stem editing, and MIDI export, plus much wider genre options and genre blending so you can chase something weird like jazz house or EDM-folk and actually get a usable track. ElevenLabs Music stays second and earns it on two fronts. In a pure A/B on vocal quality alone it still has the edge, with natural vibrato, realistic breathing, and real emotional depth, and just as important it was built on licensed and royalty-free training data from the start, which makes it the safest choice for anything commercial. Udio holds third and is the pick when you want a clean licensing story, since Universal Music Group settled with Udio back in October 2025, and its electronic and pop output is crisp and well mixed. I left every rank and score unchanged this week. There was no new model drop or legal bombshell to justify a move, so the order stands on the merits.",
   [{"title": "Suno v5 is the quality benchmark", "body": "Number one holds on an ELO around 1,293, ahead of every rival on audio fidelity, structure, and vocal realism. Suno Studio adds a DAW-like workspace, stem editing, and MIDI export, which is why it stays my daily music tool."},
    {"title": "ElevenLabs Music wins vocals and safety", "body": "Second place holds because in a pure A/B on vocal quality it still edges Suno, with natural vibrato and realistic breathing, and it was trained on licensed and royalty-free data from the start. That makes it the safest pick for commercial work."},
    {"title": "Udio is the clean-licensing choice", "body": "Udio holds third with crisp, well-mixed electronic and pop output, and its Universal Music Group settlement from October 2025 gives it the cleanest licensing story among the challengers. That matters when your track needs to clear."}],
   "Suno v5 還是品質標竿，數字也撐得起這種直覺。它的 ELO 大約 1,293，在音質、曲式結構跟人聲擬真上領先所有對手，所以第一名我給得毫不猶豫。讓它變成日常工具的是模型周邊的深度，Suno Studio 給你類 DAW 工作區、分軌編輯跟 MIDI 匯出，加上更廣的曲風選項跟混搭，你想搞點怪的像 jazz house 或 EDM-folk 都真的能出可用的歌。ElevenLabs Music 守第二，兩個面向都站得住。純比人聲品質的 A/B 它還是略勝，自然的顫音、真實的換氣跟情緒深度都到位，而且一樣重要的是它從一開始就用授權跟免版稅資料訓練，這讓它成為任何商用最安全的選擇。Udio 守第三，想要乾淨授權故事時選它，環球音樂在 2025 年十月就跟 Udio 和解了，它的電子跟流行輸出乾淨又混得好。這週名次跟分數我全沒動。沒有新模型或法律震撼彈能撐起變動，所以排序按實力站著。",
   [{"title": "Suno v5 是品質標竿", "body": "第一名守住，ELO 約 1,293，在音質、曲式跟人聲擬真上領先所有對手。Suno Studio 加了類 DAW 工作區、分軌編輯跟 MIDI 匯出，這就是它還是我日常音樂工具的原因。"},
    {"title": "ElevenLabs Music 贏在人聲跟安全", "body": "第二名守住，因為純比人聲品質的 A/B 它還是略勝 Suno，顫音自然、換氣真實，而且從一開始就用授權跟免版稅資料訓練。這讓它成為商用最安全的選擇。"},
    {"title": "Udio 是乾淨授權之選", "body": "Udio 守第三，電子跟流行輸出乾淨又混得好，加上 2025 年十月跟環球音樂的和解，讓它在挑戰者裡有最乾淨的授權故事。你的歌需要過版權時這很重要。"}])


# ---------------- AI VIDEO GENERATORS ----------------
do("best-ai-video-generators.json",
   [{"title": "Best AI Video Generator (June 2026) — Ranked by Humans", "url": "https://llm-stats.com/leaderboards/best-ai-for-video-generation", "source": "LLM-Stats"},
    {"title": "Best AI Video Generators 2026: Sora 2 vs Veo 3.1 vs Kling 3.0 vs Runway", "url": "https://www.getaiperks.com/en/blogs/44-best-ai-video-generators-2026", "source": "Get AI Perks"},
    {"title": "Best AI Video Generator in 2026: Runway, Veo, Seedance, Kling & More", "url": "https://pixflow.net/blog/best-ai-video-generator/", "source": "Pixflow"}],
   "The biggest ongoing story is the Sora exit, and it reshapes how I think about long-term pipelines. OpenAI is winding Sora down, the web and app experiences ended on April 26 and the API shuts on September 24, so anyone who built on Sora needs a migration plan now, and the obvious destinations are exactly my top names. I keep Veo 3.1 at number one. On raw fidelity it is the best, and crucially it is the only tool that generates audio in the same pass, leading on prompt adherence and 4K output in both landscape and portrait. For narrative scenes and establishing shots it is the strongest all-rounder, full stop. Runway Gen-4.5 stays second and is my pick for marketers, with reference image controls, brand-friendly character consistency, fast Turbo generations, and a real editor workflow around the model. Kling 3.0 holds third and is genuinely close to Veo on the ceiling of realism, matching it on cinematic lighting and complex motion like hair, liquids, and fabric, and adding a multi-shot storyboard mode with native audio sync across cuts. On the human-voted arena, Kling actually tops text-to-video right now, which is why the gap to Veo is narrow. I left the full ranking unchanged this week. The Sora shutdown was already priced in, so the order stands.",
   [{"title": "Veo 3.1 leads on fidelity and audio", "body": "Number one holds because Veo 3.1 is best on raw fidelity, leads prompt adherence and 4K output in landscape and portrait, and is the only tool generating audio in the same pass. For narrative and establishing shots it is the strongest all-rounder."},
    {"title": "Plan your Sora migration now", "body": "OpenAI ended the Sora web and app on April 26 and shuts the API on September 24. Any pipeline built on Sora needs to move, and Veo, Runway, and Kling are the obvious destinations, which is exactly the top of this list."},
    {"title": "Kling 3.0 is closing the gap", "body": "Kling holds third but tops the human-voted text-to-video arena right now, matching Veo on cinematic lighting and complex motion like hair and liquids, and adding multi-shot storyboards with native audio sync. The distance to first place is genuinely narrow."}],
   "目前最大的長線新聞是 Sora 退場，這改變了我對長期流程的想法。OpenAI 正在收掉 Sora，網頁跟 App 四月二十六號已經結束，API 九月二十四號關閉，所以在 Sora 上建好東西的人現在就得規劃搬遷，而最明顯的去處正是我榜單前段這幾個。我把 Veo 3.1 留第一。裸實力它最強，而且關鍵是它是唯一在同一趟就生出音訊的工具，提示詞遵循度跟橫直 4K 輸出都領先。敘事場景跟定場鏡頭它就是最強全能型，沒得談。Runway Gen-4.5 守第二，是我給行銷人的菜，有參考圖控制、對品牌友善的角色一致性、快速的 Turbo 生成，還有圍著模型的真編輯流程。Kling 3.0 守第三，寫實天花板真的逼近 Veo，在電影感打光跟頭髮、液體、布料這種複雜運動上跟它打平，還加了跨鏡頭原生音訊同步的多鏡頭分鏡模式。人類投票的競技場上，Kling 現在其實是文生影片第一，所以跟 Veo 的差距很小。這週整份名次我沒動。Sora 收攤早就反映進去了，排序照舊。",
   [{"title": "Veo 3.1 贏在擬真跟音訊", "body": "第一名守住，因為 Veo 3.1 裸實力最強，提示詞遵循度跟橫直 4K 輸出領先，而且是唯一同一趟就生出音訊的工具。敘事跟定場鏡頭它是最強全能型。"},
    {"title": "現在就規劃 Sora 搬遷", "body": "OpenAI 四月二十六號收掉 Sora 網頁跟 App，九月二十四號關 API。在 Sora 上建好的流程都得搬，Veo、Runway、Kling 是最明顯的去處，正好就是這份榜單的前段。"},
    {"title": "Kling 3.0 正在追上來", "body": "Kling 守第三，但現在在人類投票的文生影片競技場是第一，電影感打光跟頭髮、液體這種複雜運動跟 Veo 打平，還加了跨鏡頭原生音訊同步的多鏡頭分鏡。離第一真的很近。"}])


# ---------------- AI VOICE GENERATORS ----------------
do("best-ai-voice-generators.json",
   [{"title": "Voice Generation Models Compared (2026): ElevenLabs, OpenAI TTS, Hume, Cartesia, PlayHT", "url": "https://sureprompts.com/blog/voice-generation-models-compared-2026", "source": "SurePrompts"},
    {"title": "Best AI Voice Generators in 2026: APIs Ranked by Voice Quality, Latency, and Price", "url": "https://gradium.ai/content/best-ai-voice-generators-2026", "source": "Gradium"},
    {"title": "12 Best AI Voice Generators in 2026: The Listening Test", "url": "https://www.techlinos.com/post/best-ai-voice-generators/", "source": "Techlinos"}],
   "The clearest message in voice this June is that the choice is per-shot, not per-vendor. An audiobook chapter, a realtime support agent, a podcast intro, and a multilingual dub all have different right answers, and the provider that wins one rarely wins the next. That is why my ranking rewards range plus a clear specialty. ElevenLabs stays my top all-rounder pick among the named consumer tools because it is still the leader in ultra-realistic voice and professional cloning, and the v3 model localizes at scale across more than 70 languages with human-like speech, which makes it the default for audiobook narration. Hume's Octave 2 holds its slot as the emotion specialist, a voice LLM that reads script context and steers delivery through plain English instructions, so when a line genuinely needs to feel empathy or concern it is one of the most emotionally intelligent outputs you can get. Cartesia Sonic stays the latency king, targeting time-to-first-byte under 100 milliseconds, fast enough that a turn-taking agent can start replying before the user finishes their own sentence, plus instant cloning. I left every rank and score unchanged this week. The category is converging on specialization rather than a single leader, and nothing this week reordered who owns which shot, so the list stands.",
   [{"title": "Voice choice is per-shot", "body": "An audiobook chapter, a realtime agent, a podcast intro, and a multilingual dub each have a different right answer. My ranking rewards range plus a clear specialty, because the provider that wins one job rarely wins the next."},
    {"title": "ElevenLabs is the all-rounder default", "body": "Still the leader in ultra-realistic voice and professional cloning, with v3 localizing across more than 70 languages with human-like speech. That breadth makes it the default for audiobook narration and the safest first pick for most projects."},
    {"title": "Hume and Cartesia own their lanes", "body": "Hume's Octave 2 is the emotion specialist, a voice LLM that steers delivery through plain English so a line can genuinely feel empathy. Cartesia Sonic is the latency king, targeting sub-100ms time-to-first-byte for realtime turn-taking agents."}],
   "六月語音這塊最清楚的訊息就是，選擇是按用途，不是按廠商。有聲書章節、即時客服代理、Podcast 開場、多語配音，各有各的正解，贏了這個的廠商往往贏不了下一個。這就是為什麼我的榜單獎勵廣度加上明確專長。在點名的消費型工具裡，ElevenLabs 還是我的全能首選，因為它仍是極擬真語音跟專業克隆的領頭羊，v3 模型能在 70 多種語言上規模化在地化、講得跟真人一樣，這讓它成為有聲書旁白的預設。Hume 的 Octave 2 守住情感專家的位子，這是個會讀劇本脈絡、用白話英文指令調整演繹的語音 LLM，所以一句話真的需要有同理或關切時，它是你能拿到最有情緒智商的輸出之一。Cartesia Sonic 還是延遲之王，主打首位元組時間壓在 100 毫秒內，快到輪替式代理能在使用者話還沒講完就開始回，還有即時克隆。這週名次跟分數我全沒動。這個類別正往專業化收斂而非單一霸主，這禮拜也沒什麼重排了誰擅長哪一招，所以榜單照舊。",
   [{"title": "語音選擇按用途來", "body": "有聲書章節、即時代理、Podcast 開場、多語配音，各有各的正解。我的榜單獎勵廣度加上明確專長，因為贏了一個活的廠商往往贏不了下一個。"},
    {"title": "ElevenLabs 是全能預設", "body": "仍是極擬真語音跟專業克隆的領頭羊，v3 能在 70 多種語言上在地化、講得像真人。這種廣度讓它成為有聲書旁白的預設，也是多數專案最安全的第一選擇。"},
    {"title": "Hume 跟 Cartesia 各守一線", "body": "Hume 的 Octave 2 是情感專家，用白話英文調整演繹，讓一句話真能流露同理。Cartesia Sonic 是延遲之王，主打首位元組壓在 100 毫秒內，給即時輪替代理用。"}])


# ---------------- VPN SERVICES ----------------
do("best-vpn-services.json",
   [{"title": "The 3 Best VPNs of 2026", "url": "https://www.rtings.com/vpn/reviews/best/vpn", "source": "RTINGS"},
    {"title": "Mullvad vs Proton VPN: Which VPN is best in 2026?", "url": "https://cyberinsider.com/vpn/comparison/mullvad-vs-proton-vpn/", "source": "CyberInsider"},
    {"title": "Best VPN services 2026: 7 top picks for every VPN need", "url": "https://www.pcworld.com/article/406870/best-vpn-services-2.html", "source": "PCWorld"}],
   "My priorities in a VPN have not changed, and neither has the order this week. I keep Mullvad at number one because it is the undisputed king of privacy and anonymity. It actively resists knowing who you are, it does not ask for your email, your name, or anything else, and RTINGS still rates it the best overall on the balance of security, privacy, speed, reliability, and value. For me that account-number-only model is the whole point of a VPN, so it stays top. ProtonVPN holds second and is the one I steer streamers toward. It consistently outpaces Mullvad on speed for streaming, torrenting, and browsing on both local and remote servers, and it is the clear winner for Netflix, reliably getting past BBC iPlayer, Max, and Sky TV geo-blocks. If your evenings are about watching things from elsewhere, Proton is the smart pick. NordVPN stays third as the speed-first all-rounder, averaging around 72 percent of base internet speed across all servers, which is genuinely fast and makes it the easy recommendation for someone who just wants reliable performance without fuss. I left every rank and score unchanged this week. There was no breach, audit, or pricing shock to justify a move, so the list reflects the steady state, your priority decides the pick, privacy is Mullvad, streaming is Proton, raw speed is Nord.",
   [{"title": "Mullvad is the privacy king", "body": "Number one holds because Mullvad actively resists knowing who you are, asking for no email or name, just an account number. RTINGS still rates it best overall on the balance of security, privacy, speed, and value, which is exactly what a VPN should be."},
    {"title": "ProtonVPN wins streaming", "body": "Proton stays second because it outpaces Mullvad on speed for streaming, torrenting, and browsing, and reliably beats BBC iPlayer, Max, and Sky TV geo-blocks. For Netflix and watching content from elsewhere, it is the clear pick."},
    {"title": "NordVPN is the speed all-rounder", "body": "Nord holds third averaging around 72 percent of base internet speed across all servers, which is genuinely fast. For someone who just wants reliable performance without fuss, it is the easy no-drama recommendation."}],
   "我挑 VPN 的標準沒變，這週排序也沒變。我把 Mullvad 留第一，因為它是隱私跟匿名當之無愧的王。它主動不想知道你是誰，不問你的 email、不問名字、什麼都不問，RTINGS 也還是在安全、隱私、速度、可靠跟價值的平衡上把它評為整體最佳。對我來說那種只給帳號的模式就是 VPN 的全部意義，所以它穩坐第一。ProtonVPN 守第二，是我會推給追劇族的那個。它在串流、torrent 跟瀏覽的速度上不論本地或遠端伺服器都穩定贏過 Mullvad，看 Netflix 更是明顯的贏家，能可靠繞過 BBC iPlayer、Max 跟 Sky TV 的地區封鎖。你晚上都在看別國的東西的話，Proton 是聰明的選擇。NordVPN 守第三，速度優先的全能型，全伺服器平均約有基礎網速的 72 趴，這真的很快，誰只想要穩定效能不囉嗦就推它。這週名次跟分數我全沒動。沒有外洩、稽核或價格震撼能撐起變動，所以榜單反映平穩狀態，你的優先順序決定怎麼選，要隱私選 Mullvad，要追劇選 Proton，要純速度選 Nord。",
   [{"title": "Mullvad 是隱私之王", "body": "第一名守住，因為 Mullvad 主動不想知道你是誰，不問 email 不問名字，只要一組帳號。RTINGS 也還在安全、隱私、速度跟價值的平衡上把它評為整體最佳，這正是 VPN 該有的樣子。"},
    {"title": "ProtonVPN 贏在串流", "body": "Proton 守第二，因為它在串流、torrent 跟瀏覽的速度上贏過 Mullvad，還能可靠繞過 BBC iPlayer、Max 跟 Sky TV 的地區封鎖。看 Netflix 跟追別國內容它是明顯首選。"},
    {"title": "NordVPN 是速度全能型", "body": "Nord 守第三，全伺服器平均約基礎網速的 72 趴，真的很快。誰只想要穩定效能不想囉嗦，它就是最不費神的推薦。"}])

print("ALL DONE")
